apiVersion: v1
kind: Service
metadata:
  name: chat-gke-service
  namespace: chatroom
  labels:
    app: chat-webapp
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: chat-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
