apiVersion: v1
kind: Service
metadata:
  name: frontend-gke-service
  namespace: backend
  labels:
    app: frontend-webapp
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  selector:
    app: frontend-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
