name: Checkov Checks

# 3 parallel jobs that run in parallel and needs no dependencies.
# 1. Checkov Terraform
# 2. Checkov Kubernetes
# 3. Checkov Dockerized Application

on:
  push:
    branches: [main, master] # runs on both main and master branches, I have only main branch for now

jobs:
  checkov-Terraform:
    name: Checkov Checks on GKE Terraform

    #---------------TO RUN ON MULTIPLE OSs---------------------------------
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os:
    #       - "ubuntu-latest"
    #       - "windows-latest"
    #       - "macos-latest"
    # runs-on: "${{ matrix.os }}"
    #----------------------------------------------------------------------

    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov Install
        working-directory: ./GKE-Terraform
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install checkov

      - name: Checkov Test Run
        working-directory: ./GKE-Terraform
        run: |
          checkov -d .

  checkov-Kubernetes:
    name: Checkov Checks on K8S manifests

    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov Install
        working-directory: ./chatroom-manifest
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install checkov

      - name: Checkov Test Run
        working-directory: ./chatroom-manifest
        run: |
          checkov -d .

  checkov-github-workflow:
    name: Checkov Checks on application

    runs-on: ubuntu-latest
    needs: []

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov Install
        working-directory: ./chatroom-application
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install checkov

      - name: Checkov Test Run
        working-directory: ./chatroom-application
        run: |
          checkov -d .
