name: Checkov Checks

on:
  push:
    branches: [main, master]

jobs:
  checkov:
    name: Checkov Checks
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
    runs-on: "${{ matrix.os }}"
    needs: []

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkov Install
        working-directory: ./GKE-Terraform
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install checkov

      - name: Checkov Test Run
        working-directory: ./GKE-Terraform
        run: |
          checkov -d .
