name: Checkov Checks

on:
  push:
    branches: [main]

jobs:
  checkov:
    name: Checkov Checks
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: Checkov Install
        run: |
          sudo apt-get install -y python3-pip
          sudo pip3 install checkov
      - name: Checkov Test Run
        working-directory: ./GKE-Terraform
        run: |
          checkov -f .
