name: Terraform GCP-GKE

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Google Cloud CLIS
        run: |
          apt-get install apt-transport-https ca-certificates gnupg curl 
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.asc] https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | tee /usr/share/keyrings/cloud.google.asc

          apt-get update && apt-get install google-cloud-cli
      # gcloud auth activate-service-account --key-file ${{secrets.GCLOUD_CREDENTIALS}}
      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add - && apt-add-
          apt-get update && apt-get install terraform

      - name: Terraform Init
        working-directory: ./GKE-Terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./GKE-Terraform
        run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
