name: Terraform GCP-GKE
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: stp-7thsem
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          service_account_key: ${{ secrets.GCLOUD_CREDENTIALS }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Terraform initialize
        working-directory: ./GKE-Terraform
        run: terraform init

      - name: Terraform plan
        working-directory: ./GKE-Terraform
        run: terraform plan -out=tfplan.out
